
export const OFFICIAL_TEAM = [
  { firstName: 'Daniel', lastName: 'de la Rosa' },
  { firstName: 'Misael', lastName: 'Martínez' },
  { firstName: 'Fernando', lastName: 'Paramo' },
  { firstName: 'Victor', lastName: 'Torres' },
  { firstName: 'Cesar', lastName: 'Nieto' },
  { firstName: 'Abraham', lastName: 'Luevano' },
  { firstName: 'Daniel', lastName: 'Torres' },
  { firstName: 'Enrique', lastName: 'Oropeza' },
  { firstName: 'Eduardo', lastName: 'Ferrusca' },
  { firstName: 'Agustín', lastName: 'Tellez' },
  { firstName: 'Fransisco', lastName: 'Aguilar' },
  { firstName: 'Adrian', lastName: 'Balderas' },
  { firstName: 'Ricardo', lastName: 'Cortes' },
  { firstName: 'David', lastName: 'Mejia' },
  { firstName: 'Mariel', lastName: 'Quezada' },
  { firstName: 'Jose Francisco', lastName: 'Morales' },
  { firstName: 'Alberto', lastName: 'Balbuena' }
];

export const OFFICIAL_DESTINATIONS = [
  { name: 'QRO', type: 'long', pointsValue: 1, paymentAmount: 211 },
  { name: 'Puebla', type: 'long', pointsValue: 1, paymentAmount: 250 },
  { name: 'Chilpancingo', type: 'long', pointsValue: 1, paymentAmount: 280 },
  { name: 'Morelia', type: 'long', pointsValue: 1, paymentAmount: 305 },
  { name: 'León', type: 'long', pointsValue: 1, paymentAmount: 384 },
  { name: 'Veracruz', type: 'long', pointsValue: 1, paymentAmount: 392 },
  { name: 'Acapulco', type: 'long', pointsValue: 1, paymentAmount: 395 },
  { name: 'SLP', type: 'long', pointsValue: 1, paymentAmount: 417 },
  { name: 'Oaxaca', type: 'long', pointsValue: 1, paymentAmount: 483 },
  { name: 'Aguascalientes', type: 'long', pointsValue: 1, paymentAmount: 484 },
  { name: 'Zihuatanejo', type: 'long', pointsValue: 1, paymentAmount: 491 },
  { name: 'GDL', type: 'long', pointsValue: 1, paymentAmount: 531 },
  { name: 'Zacatecas', type: 'long', pointsValue: 1, paymentAmount: 611 },
  { name: 'Pto Escondido', type: 'long', pointsValue: 1, paymentAmount: 673 },
  { name: 'Huatulco', type: 'long', pointsValue: 1, paymentAmount: 746 },
  { name: 'Villahermosa', type: 'long', pointsValue: 1, paymentAmount: 753 },
  { name: 'Nayarit', type: 'long', pointsValue: 1, paymentAmount: 781 },
  { name: 'Chiapas', type: 'long', pointsValue: 1, paymentAmount: 832 },
  { name: 'Pto V', type: 'long', pointsValue: 1, paymentAmount: 846 },
  { name: 'Saltillo', type: 'long', pointsValue: 1, paymentAmount: 853 },
  { name: 'Durango', type: 'long', pointsValue: 1, paymentAmount: 880 },
  { name: 'Monterrey', type: 'long', pointsValue: 1, paymentAmount: 942 },
  { name: 'Torreón', type: 'long', pointsValue: 1, paymentAmount: 989 },
  { name: 'Mazatlán', type: 'long', pointsValue: 1, paymentAmount: 1005 },
  { name: 'Culiacán', type: 'long', pointsValue: 1, paymentAmount: 1222 },
  { name: 'Mérida', type: 'long', pointsValue: 1, paymentAmount: 1294 },
  { name: 'Chihuahua', type: 'long', pointsValue: 1, paymentAmount: 1426 },
  { name: 'Cancún', type: 'long', pointsValue: 1, paymentAmount: 1683 },
  { name: 'Cd Juárez', type: 'long', pointsValue: 1, paymentAmount: 1782 },
  { name: 'Hermosillo', type: 'long', pointsValue: 1, paymentAmount: 1903 },
  { name: 'Tijuana', type: 'long', pointsValue: 1, paymentAmount: 2759 }
];
